cmodel_path="./trained_models/cmodel/nli-deberta-v3-large"
smodel_path="./trained_models/smodel/bert-base-chinese"
docrec_model_path="./trained_models/docrecmodel/"
stnrec_model_path="./trained_models/stnrecmodel/macbert4csc-base-chinese"
split_pattern=r"[^，。、：\n]+"